"""
Given two strings s and t of equal length, the Hamming distance between s and t, denoted dH(s,t),
is the number of corresponding symbols that differ in s and t.

Given: Two DNA strings s and t of equal length (not exceeding 1 kbp).

Return: The Hamming distance dH(s,t).

Sample:
GAGCCTACTAACGGGAT
CATCGTAATGACGGCCT

Output:
7
"""

S1 = "ATACGGTGACCGCACCGAATAGACATGCGGTGACCATTTTGAACCAACTCGCGCTGGAGGCTACACATCCCGCTAATGAGACGACCCGCGAGTTCATCTTTATTGA" \
     "GGCTACCTTCCAAAAATAGAGCAACAGCTATAAAGGAAACCTCTTTAAACATCTACACCCGAATTTATGATTTGTTACCGAGGACTGAGACCTTGGGAGGATTATA" \
     "CACATAATCAATTACCGTGAAAAAATGGGAGGAGGAGCGACACTTCCACACGTCCCTGCAAGAGGACAGAAACATATGAATTAGGCTCCACGCTCTACTCTGATCC" \
     "GTTCGCCGAAGCATTGTAACTGGATGAGCAGGTTTGTTCCCCCAGTAAAGGAACCGTCCTGAATCAATAAAGATTGGCCGGGCGCACGCCGCCTCCGGTGTCCGAT" \
     "GCCTCACACTTCCGGTAAGATTTTATGACCTGGTGACGGTCTTGGAGTGTTAGGGGAAGTGATAACAGGACATGCAATAAAGAGTATGAACTGAACCGCATCGAGA" \
     "AGGGTTACCACCGCTGTCAGCGTCGGCGACTATAGAATATCTTGCAACTTAGCGAGTCCATGGGCATTGTTGAGGCAGTGTGGACTAAAGCCACTTCCGCCTTGCC" \
     "GGGACCCGTAGGCGGACTGCATCCGGCACCTGGACGATGTACGCCTGAAAATCATCCAAGCTCTGATCTTCAGTAGCGACTTACGCTGTTGACACGGATATGAAGA" \
     "CTGCGACTTGAAACTTAGCGGGCGGGCACTTCATGACAACCTAGGTCCAGAGTCACTTCGTCCGAACCGGAAGATGATAAGGCCACCGAGCGTTTCGTGACGGTAT" \
     "GTCTGACCGCTCGAACACCAGGGAAAACCCCTTTCGCACTCGGAGGTTATTTGCAACCGGCGGGCTAGCTGGCAGCCTAGAACAGGGATATGAAATATGGTTAATG" \
     "GATAGCTACGACCATAGCTTTGTCCACTACCATAGCTCGCTT"
S2 = "GTCGGGGGTCCAGTCCGTCTTGGGATGACGAGACGATTACGCAGAAGCATGCGCTTCATGCCAGGGATCGCGCAAGTCCGTGAAACAGGGGGATCATCTCTTCAGA" \
     "CGCTACCGTACAAGCATAATGCTTCGGCCGCCGCGGATTACCCTAATGAGTTCCACCTCCGAATAAATGATTTGATAAGGGTCAACACCGCCATACCAACTTCAAG" \
     "TAACTATTCAACTACTATAACCGATGGGGTGGAGGTTCCTCAGTGCCAGACCTAGCGGCCAGAGGACCGACACGTGCTAGTTATCCGGAACTGGTTAATACGGGGT" \
     "GTGAGGCGAGCAAAAGAGGCAAGTTGAGCAGGTGAGCAACTTCAGGCATCGAGCCGTGATTGGTGGGTCACGCTGAGCTGAGCTCAGCCTGCCTCCGGCGTCCGAT" \
     "TGGTCACATATATGGGACTGTCGTATGTTGGGTGTACGCTCTTGGACATTTAACATCAGTGTTTGAGGACTTAGCTTTCTTGGGTATGGAATGCCCCGCAGCGAAG" \
     "TGGGCAAGCATAGAGGGAAATTGACTCGATCACTGGGAAGAGAGCCTATCAGCAACTGCTTTCCGGTTCTTAAGTTGTTGTAAGCAATCGAAGCAATCGACTTAGG" \
     "GGTACTAGTATTAGGTCGCAGTTGGGTAGGAGCATTCTAATCATCTAACGTTTAAGAAACGCCTGAAGTATAGTAGCTAATTACATTGTCCACAGGCGTCTGTGGA" \
     "CAGAGACTGGAGGCTTACGAGTGTTAAGCGCCACTGAAAACCACGTCGTGTTGCACTTCAACCGAATCCGAAAACACTCCTCCCCTCCGGGGCTACTTGGCAGCAG" \
     "GCCCGCCCGCGCCTTTATATGCTCCGACAACACTCACCCAAGAGTTTTGTGTTCTACGGTCTGTCGATTGTGAATAGTGTAAAAATGATCAAGAGAGCAGTTGAGG" \
     "TATAACATCGACCTTCGCTCTGTACAAAGATGACGATGCCTT "
dh = 0

print(sum([a != b for a, b in zip(S1, S2)]))

for i in range(len(S1)):
    if S1[i] != S2[i]:
        dh += 1
print(dh)
